pipeline {
  environment {
    AWS_ACCESS_KEY_ID = credentials('f9802c39-09e6-4640-ae78-324e3c1ad845')
    AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
  }
    agent any
  stages {
    stage('git checkout') {
        steps {
    git branch: 'main', url: 'https://github.com/pravi0306/devops.git'
        }
}
  stage('terraform init') {
    steps {
    dir('devops') {
        sh 'terraform init'
    }
    }
  }
  stage('terraform plan') {
    steps {
    dir('devops') {
        sh 'terraform plan -input=false'
    }
    }
  }
   stage('terraform action') {
    steps {
        sh 'terraform ${action} --auto-approve'
    }
  }
  }    
}